services:

  gateway:
    enabled: true
    name: gateway-service
    registry: ecr
    imageTag: gateway-service-latest
    port: 8080
    databaseEnabled: false
    env:
      AUTH_SERVICE_URL: "http://auth-service:8081"
      USER_SERVICE_URL: "http://user-service:8082"

  auth:
    enabled: true
    name: auth-service
    registry: ecr
    imageTag: auth-service-latest
    port: 8081
    databaseEnabled: true

  user:
    enabled: true
    name: user-service
    registry: nexus
    imageTag: user-service-latest
    port: 8082
    databaseEnabled: true

  admin:
    enabled: true
    name: admin-service
    registry: nexus
    imageTag: admin-service-latest
    port: 8082
    databaseEnabled: true

  employee:
    enabled: true
    name: employee-service
    registry: nexus
    imageTag: employee-service-latest
    port: 8083
    databaseEnabled: true

  customer:
    enabled: true
    name: customer-service
    registry: nexus
    imageTag: customer-service-latest
    port: 8084
    databaseEnabled: true

  hr:
    enabled: true
    name: hr-service
    registry: nexus
    imageTag: hr-service-latest
    port: 8085
    databaseEnabled: true

  task:
    enabled: true
    name: task-service
    registry: nexus
    imageTag: task-service-latest
    port: 8089
    databaseEnabled: true
